### PR TITLE
Live customization

### PR DESCRIPTION
**Pull request by Cananito**
@mmorey Review.

Issue https://github.com/chaione/CHCircleGauge/issues/8

### CODE REVIEW

**Comment by mmorey** [comment]
For the color selection maybe we can utilize one of these:
- https://github.com/hayashi311/Color-Picker-for-iOS
- https://github.com/regexident/DLColorPicker
- https://github.com/InfinitApps/InfColorPicker
- https://github.com/leoru/KKColorListPicker
- and many more http://cocoapods.org/?q=color%20picker

**Comment by mmorey** [comment]
Also need to update the GIF animation now.

**Comment by Cananito** [comment]
@mmorey Added color editing, review again.

**Comment by mmorey** [comment]
Looks good but lets link the color up with the buttons, see screenshot. Also, lets make the default colors something other than black.

ios_simulator_-_iphone_retina__3_5-inch____ios_7_1__11d167_

**Comment by mmorey** [comment]
Should we set the title of the nav bar to CHCircleGauge?

**Comment by Cananito** [comment]
@mmorey Did a few changes.

**Pull request merged**
